=== KKrisztian2/WIQPM2_XMLGyak/XMLTaskWIQPM2/XMLSchemaWIQPM2.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- Egyszerű típusok -->
<xs:element name="tipus" type="xs:string" />
<xs:element name="sz_orszag" type="xs:string" />
<xs:element name="tulajdonos" type="xs:string" />

<xs:element name="miota_szp" type="xs:string" />

<xs:element name="j_nev" type="xs:string" />
<xs:element name="j_nemzetiseg" type="xs:string" />
<xs:element name="aktiv" type="aktivTipus" />
<xs:element name="j_rang" type="xs:string" />
<xs:element name="pozicio" type="pozicioTipus" />
<xs:element name="karrier_kezdete" type="xs:gYear" />
<xs:element name="eletkor" type="xs:integer" />

<xs:element name="cs_nemzetiseg" type="xs:string" />
<xs:element name="cs_rang" type="xs:integer" />
<xs:element name="regio" type="xs:string" />

<xs:element name="e_nev" type="xs:string" />
<xs:element name="miota" type="xs:gYear" />
<xs:element name="korabbi_csapat" type="xs:string" />

<xs:element name="es_nev" type="xs:string" />
<xs:element name="ev" type="xs:gYear" />
<xs:element name="nyeremeny" type="xs:integer" />
<xs:element name="es_orszag" type="xs:string" />
<xs:element name="varos" type="xs:string" />
<xs:element name="hely" type="xs:string" />


 <!-- Saját típusok létrehozása  -->
<xs:simpleType name="aktivTipus">
    <xs:restriction base="xs:string">
        <xs:enumeration value="Igen" />
        <xs:enumeration value="Nem" />      
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="pozicioTipus">
    <xs:restriction base="xs:string">
        <xs:enumeration value="Top" />
        <xs:enumeration value="Mid" />
        <xs:enumeration value="Bottom" />
        <xs:enumeration value="Support" />
        <xs:enumeration value="Jungle" />
    </xs:restriction>
</xs:simpleType>


<!-- Komplex típushoz sajat típus létrehozása-->
<xs:complexType name="szponzorTipus">
    <xs:sequence>
        <xs:element ref="tipus" />           
        <xs:element ref="sz_orszag" />
        <xs:element name="tulajdonos" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="sz_nev" type="xs:string" use="required" />
</xs:complexType>

<xs:complexType name="szp_csapatTipus">
    <xs:sequence>
        <xs:element ref="miota_szp" />
    </xs:sequence>
    <xs:attribute name="szp_csapat_azonosito" type="xs:integer" use="required" />
    <xs:attribute name="szp_nev" type="xs:string" use="required" />
    <xs:attribute name="csapat_nev" type="xs:string" use="required" />
</xs:complexType>

<xs:complexType name="jatekosTipus">
    <xs:sequence>
        <xs:element ref="j_nev" />           
        <xs:element ref="j_nemzetiseg" />
        <xs:element ref="aktiv" />           
        <xs:element ref="j_rang" />
        <xs:element ref="pozicio" />           
        <xs:element ref="karrier_kezdete" />
        <xs:element ref="eletkor" />
    </xs:sequence>
    <xs:attribute name="j_azonosito" type="xs:integer" use="required" />
    <xs:attribute name="csapat_nev" type="xs:string" use="required" />
</xs:complexType>

<xs:complexType name="csapatTipus">
    <xs:sequence>
        <xs:element ref="cs_nemzetiseg" />           
        <xs:element ref="cs_rang" />
        <xs:element ref="regio" />
    </xs:sequence>
    <xs:attribute name="cs_nev" type="xs:string" use="required" />
</xs:complexType>

<xs:complexType name="edzoTipus">
    <xs:sequence>
        <xs:element ref="e_nev" />           
        <xs:element ref="miota" />
        <xs:element ref="korabbi_csapat" />
    </xs:sequence>
    <xs:attribute name="e_azonosito" type="xs:integer" use="required" />
    <xs:attribute name="csapat_nev" type="xs:string" use="required" />
</xs:complexType>

<xs:complexType name="esemenyTipus">
    <xs:sequence>
        <xs:element ref="es_nev" />           
        <xs:element ref="ev" />
        <xs:element ref="nyeremeny" />
        <xs:element name = "helyszin">
            <xs:complexType mixed = "true">
                <xs:sequence>
                    <xs:element name="es_orszag" type="xs:string" />
                    <xs:element name="varos" type="xs:string" />
                    <xs:element name="hely" type="xs:string" />
                </xs:sequence>
            </xs:complexType>
        </xs:element>
    </xs:sequence>
    <xs:attribute name="es_azonosito" type="xs:integer" use="required" />
    <xs:attribute name="csapat_nev" type="xs:string" use="required" />
</xs:complexType>


<!-- Az elemek sorrendisége a gyökérelemtől -->
<xs:element name="LoL_WIQPM2">
    <xs:complexType>
        <xs:sequence>

            <xs:element name="szponzorok">
                <xs:complexType mixed = "true">
                    <xs:sequence>
                        <xs:element name="szponzor" type="szponzorTipus" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="szp_csapatok">
                <xs:complexType mixed = "true">
                    <xs:sequence>
                        <xs:element name="szp_csapat" type="szp_csapatTipus" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="jatekosok">
                <xs:complexType mixed = "true">
                    <xs:sequence>
                        <xs:element name="jatekos" type="jatekosTipus" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="csapatok">
                <xs:complexType mixed = "true">
                    <xs:sequence>
                        <xs:element name="csapat" type="csapatTipus" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="edzok">
                <xs:complexType mixed = "true">
                    <xs:sequence>
                        <xs:element name="edzo" type="edzoTipus" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="esemenyek">
                <xs:complexType mixed = "true">
                    <xs:sequence>
                        <xs:element name="esemeny" type="esemenyTipus" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

        </xs:sequence>
    </xs:complexType>


    <!-- Elsődleges kulcsok létrehozása-->
    <xs:key name="szponzor_kulcs">
        <xs:selector xpath="szponzor"/>
        <xs:field xpath="@sz_nev"/>
    </xs:key>
    <xs:key name="szp_csapat_kulcs">
        <xs:selector xpath="szp_csapat"/>
        <xs:field xpath="@szp_csapat_azonosito"/>
    </xs:key>
    <xs:key name="jatekos_kulcs">
        <xs:selector xpath="jatekos"/>
        <xs:field xpath="@j_azonosito"/>
    </xs:key>
    <xs:key name="csapat_kulcs">
        <xs:selector xpath="csapat"/>
        <xs:field xpath="@cs_nev"/>
    </xs:key>
    <xs:key name="edzo_kulcs">
        <xs:selector xpath="edzo"/>
        <xs:field xpath="@e_azonosito"/>
    </xs:key>
    <xs:key name="esemeny_kulcs">
        <xs:selector xpath="esemeny"/>
        <xs:field xpath="@es_azonosito"/>
    </xs:key>


    <!-- Idegen kulcsok létrehozása -->
    <xs:keyref name="szp_csapat_szp_ikulcs" refer="szponzor_kulcs">
        <xs:selector xpath="szp_csapat"/>
        <xs:field xpath="@szponzor"/>
    </xs:keyref>
    <xs:keyref name="szp_csapat_csapat_ikulcs" refer="csapat_kulcs">
        <xs:selector xpath="szp_csapat"/>
        <xs:field xpath="@csapat"/>
    </xs:keyref>
    <xs:keyref name="jatekos_csapat_ikulcs" refer="csapat_kulcs">
        <xs:selector xpath="jatekos"/>
        <xs:field xpath="@csapat"/>
    </xs:keyref>
    <xs:keyref name="edzo_csapat_ikulcs" refer="csapat_kulcs">
        <xs:selector xpath="edzo"/>
        <xs:field xpath="@csapat"/>
    </xs:keyref>
    <xs:keyref name="esemeny_csapat_ikulcs" refer="esemeny_kulcs">
        <xs:selector xpath="esemeny"/>
        <xs:field xpath="@csapat"/>
    </xs:keyref>


    <!-- 1:1 kapcsolat -->
    <xs:unique name="csapat_edzo_egyedi">
        <xs:selector xpath="edzo"/>
        <xs:field xpath="@csapat"/>
    </xs:unique>

</xs:element>


</xs:schema>

=== KKrisztian2/WIQPM2_XMLGyak/XMLTaskWIQPM2_vegeleges/XMLWIQPM21.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<LoL_WIQPM2 xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaWIQPM2.xsd">
     <szponzorok>
          <szponzor sz_nev="Monster Energy">
               <tipus>Energiaital</tipus>
               <sz_orszag>USA</sz_orszag>
               <tulajdonos>Rodney Sacks</tulajdonos>
          </szponzor>
          <szponzor sz_nev="SteelSeries">
               <tipus>Gaming</tipus>
               <sz_orszag>Norvégia</sz_orszag>
               <tulajdonos>Ehtisham Rabbani</tulajdonos>
               <tulajdonos>Tino Soelberg</tulajdonos>
               <tulajdonos>Oluf Riddersholm</tulajdonos>
          </szponzor>
          <szponzor sz_nev="Twitch">
               <tipus>Streamingszolgáltatás</tipus>
               <sz_orszag>USA</sz_orszag>
               <tulajdonos>Twitch Interactive</tulajdonos>
          </szponzor>
     </szponzorok>
     <szp_csapatok>
          <szp_csapat csapat_nev="Fnatic" szp_csapat_azonosito="1" szp_nev="Monster Energy">
               <miota_szp>2017</miota_szp>
          </szp_csapat>
          <szp_csapat csapat_nev="Team Liquid" szp_csapat_azonosito="2" szp_nev="SteelSeries">
               <miota_szp>2018</miota_szp>
          </szp_csapat>
          <szp_csapat csapat_nev="PSG Talon" szp_csapat_azonosito="3" szp_nev="Twitch">
               <miota_szp>2020</miota_szp>
          </szp_csapat>
     </szp_csapatok>
     <jatekosok>
          <jatekos csapat_nev="Fnatic" j_azonosito="1">
               <j_nev>Humanoid</j_nev>
               <j_nemzetiseg>cseh</j_nemzetiseg>
               <aktiv>Igen</aktiv>
               <j_rang>62</j_rang>
               <pozicio>Mid</pozicio>
               <karrier_kezdete>2016</karrier_kezdete>
               <eletkor>23</eletkor>
          </jatekos>
          <jatekos csapat_nev="Fnatic" j_azonosito="2">
               <j_nev>Razork</j_nev>
               <j_nemzetiseg>spanyol</j_nemzetiseg>
               <aktiv>Igen</aktiv>
               <j_rang>167</j_rang>
               <pozicio>Jungle</pozicio>
               <karrier_kezdete>2016</karrier_kezdete>
               <eletkor>23</eletkor>
          </jatekos>
          <jatekos csapat_nev="Team Liquid" j_azonosito="3">
               <j_nev>CoreJJ</j_nev>
               <j_nemzetiseg>dél koreai</j_nemzetiseg>
               <aktiv>Igen</aktiv>
               <j_rang>69</j_rang>
               <pozicio>Support</pozicio>
               <karrier_kezdete>2013</karrier_kezdete>
               <eletkor>29</eletkor>
          </jatekos>
     </jatekosok>
     <csapatok>
          <csapat cs_nev="Fnatic">
               <cs_nemzetiseg>Anglia</cs_nemzetiseg>
               <cs_rang>14</cs_rang>
               <regio>EMEA</regio>
          </csapat>
          <csapat cs_nev="Team Liquid">
               <cs_nemzetiseg>Hollandia</cs_nemzetiseg>
               <cs_rang>15</cs_rang>
               <regio>NA</regio>
          </csapat>
          <csapat cs_nev="PSG Talon">
               <cs_nemzetiseg>Kína</cs_nemzetiseg>
               <cs_rang>22</cs_rang>
               <regio>PCS</regio>
          </csapat>
     </csapatok>
     <edzok>
          <edzo csapat_nev="Fnatic" e_azonosito="1">
               <e_nev>Nightshare</e_nev>
               <miota>2023</miota>
               <korabbi_csapat>Immortals</korabbi_csapat>
          </edzo>
          <edzo csapat_nev="Team Liquid" e_azonosito="2">
               <e_nev>Spawn</e_nev>
               <miota>2023</miota>
               <korabbi_csapat>TL Challengers</korabbi_csapat>
          </edzo>
          <edzo csapat_nev="PSG Talon" e_azonosito="3">
               <e_nev>CorGi</e_nev>
               <miota>2021</miota>
               <korabbi_csapat>EDward Gaming</korabbi_csapat>
          </edzo>
     </edzok>
     <esemenyek>
          <esemeny csapat_nev="Fnatic" es_azonosito="1">
               <es_nev>Rift Rivals 2018 NA-EU</es_nev>
               <ev>2018</ev>
               <nyeremeny>20000</nyeremeny>
               <helyszin>
                    <es_orszag>US</es_orszag>
                    <varos>Los Angeles</varos>
                    <hely>Riot North American Studios</hely>
               </helyszin>
          </esemeny>
          <esemeny csapat_nev="Fnatic" es_azonosito="2">
               <es_nev>EU LCS 2015 Summer Playoffs</es_nev>
               <ev>2015</ev>
               <nyeremeny>50000</nyeremeny>
               <helyszin>
                    <es_orszag>Svédország</es_orszag>
                    <varos>Stockholm</varos>
                    <hely>Hovet Arena</hely>
               </helyszin>
          </esemeny>
          <esemeny csapat_nev="Team Liquid" es_azonosito="3">
               <es_nev> LCS 2022 Lock In</es_nev>
               <ev>2022</ev>
               <nyeremeny>150000</nyeremeny>
               <helyszin>
                    <es_orszag>US</es_orszag>
                    <varos>Los Angeles</varos>
                    <hely>LCS Studio</hely>
               </helyszin>
          </esemeny>
     </esemenyek>
</LoL_WIQPM2>

=== KKrisztian2/WIQPM2_XMLGyak/XMLTaskWIQPM2/XMLWIQPM2.xml
<?xml version="1.0" encoding="UTF-8"?>

<LoL_WIQPM2 xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="XMLSchemaWIQPM2.xsd">

    <!-- Szponzorok -->
    <szponzorok>
        <szponzor sz_nev = "Hana Bank">
            <tipus>Bank</tipus>
            <sz_orszag>Dél-Korea</sz_orszag>
            <tulajdonos>Park Sung-ho</tulajdonos>
        </szponzor>
        <szponzor sz_nev = "Twitch">
            <tipus>Streamingszolgáltatás</tipus>
            <sz_orszag>USA</sz_orszag>
            <tulajdonos>Twitch Interactive</tulajdonos>
        </szponzor>
        <szponzor sz_nev = "BMW">
            <tipus>Járműipar</tipus>
            <sz_orszag>Németország</sz_orszag>
            <tulajdonos>Stefan Quandt</tulajdonos>
            <tulajdonos>Susanne Klatten</tulajdonos>
            <tulajdonos>BlackRock</tulajdonos>
        </szponzor>
    </szponzorok>

    <!-- Szp csapat-->
    <szp_csapatok>
        <szp_csapat szp_csapat_azonosito = "1" szp_nev = "BMW" csapat_nev = "G2">
            <miota_szp>2018</miota_szp>
        </szp_csapat>
        <szp_csapat szp_csapat_azonosito = "2" szp_nev = "Twitch" csapat_nev = "G2">
            <miota_szp>2020</miota_szp>
        </szp_csapat>
        <szp_csapat szp_csapat_azonosito = "3" szp_nev = "Hana Bank" csapat_nev = "T1">
            <miota_szp>2022</miota_szp>
        </szp_csapat>
    </szp_csapatok>

    <!-- Játékosok -->
    <jatekosok>
        <jatekos j_azonosito = "1" csapat_nev = "G2">
            <j_nev>BrokenBlade</j_nev>
            <j_nemzetiseg>német</j_nemzetiseg>
            <aktiv>Igen</aktiv>
            <j_rang>77</j_rang>
            <pozicio>Top</pozicio>
            <karrier_kezdete>2016</karrier_kezdete>
            <eletkor>23</eletkor>
        </jatekos>
        <jatekos j_azonosito = "2" csapat_nev = "G2">
            <j_nev>Yike</j_nev>
            <j_nemzetiseg>svéd</j_nemzetiseg>
            <aktiv>Igen</aktiv>
            <j_rang>203</j_rang>
            <pozicio>Jungle</pozicio>
            <karrier_kezdete>2019</karrier_kezdete>
            <eletkor>23</eletkor>
        </jatekos>
        <jatekos j_azonosito = "3" csapat_nev = "G2">
            <j_nev>Caps</j_nev>
            <j_nemzetiseg>norvég</j_nemzetiseg>
            <aktiv>Igen</aktiv>
            <j_rang>21</j_rang>
            <pozicio>Mid</pozicio>
            <karrier_kezdete>2015</karrier_kezdete>
            <eletkor>24</eletkor>
        </jatekos>
        <jatekos j_azonosito = "4" csapat_nev = "G2">
            <j_nev>Hans Sama</j_nev>
            <j_nemzetiseg>francia</j_nemzetiseg>
            <aktiv>Igen</aktiv>
            <j_rang>83</j_rang>
            <pozicio>Bottom</pozicio>
            <karrier_kezdete>2014</karrier_kezdete>
            <eletkor>24</eletkor>
        </jatekos>
        <jatekos j_azonosito = "5" csapat_nev = "G2">
            <j_nev>Mikyx</j_nev>
            <j_nemzetiseg>szlovén</j_nemzetiseg>
            <aktiv>Igen</aktiv>
            <j_rang>31</j_rang>
            <pozicio>Support</pozicio>
            <karrier_kezdete>2014</karrier_kezdete>
            <eletkor>25</eletkor>
        </jatekos>
        <jatekos j_azonosito = "6" csapat_nev = "T1">
            <j_nev>Faker</j_nev>
            <j_nemzetiseg>dél koreai</j_nemzetiseg>
            <aktiv>Igen</aktiv>
            <j_rang>2</j_rang>
            <pozicio>Mid</pozicio>
            <karrier_kezdete>2013</karrier_kezdete>
            <eletkor>27</eletkor>
        </jatekos>
    </jatekosok>

    <!-- Csapatok -->
    <csapatok>
        <csapat cs_nev = "T1">
            <cs_nemzetiseg>Dél-Korea</cs_nemzetiseg>
            <cs_rang>1</cs_rang>
            <regio>LCK</regio>
        </csapat>
        <csapat cs_nev = "G2">
            <cs_nemzetiseg>Németország</cs_nemzetiseg>
            <cs_rang>6</cs_rang>
            <regio>LEC</regio>
        </csapat>
        <csapat cs_nev = "Mad Lions">
            <cs_nemzetiseg>Spanyolország</cs_nemzetiseg>
            <cs_rang>16</cs_rang>
            <regio>LEC</regio>
        </csapat>
        <csapat cs_nev = "JD Gaming">
            <cs_nemzetiseg>Kína</cs_nemzetiseg>
            <cs_rang>4</cs_rang>
            <regio>LPL</regio>
        </csapat>
    </csapatok>

    <!-- Edzők -->
    <edzok>
        <edzo e_azonosito = "1" csapat_nev = "G2">
            <e_nev>Dylan Falco</e_nev>
            <miota>2021</miota>
            <korabbi_csapat>Schalke 04</korabbi_csapat>
        </edzo>
        <edzo e_azonosito = "2" csapat_nev = "T1">
            <e_nev>kK0ma</e_nev>
            <miota>2023</miota>
            <korabbi_csapat>DWG Kia</korabbi_csapat>
        </edzo>
        <edzo e_azonosito = "3" csapat_nev = "Mad Lions">
            <e_nev>Mac</e_nev>
            <miota>2019</miota>
            <korabbi_csapat>Splyce</korabbi_csapat>
        </edzo>
        <edzo e_azonosito = "4" csapat_nev = "JD Gaming">
            <e_nev>Mafa</e_nev>
            <miota>2023</miota>
            <korabbi_csapat>Gen.G</korabbi_csapat>
        </edzo>
    </edzok>

    <!-- Események -->
    <esemenyek>
        <esemeny es_azonosito = "1" csapat_nev = "G2">
            <es_nev>LEC 2023 Season Finals</es_nev>
            <ev>2023</ev>
            <nyeremeny>65000</nyeremeny>
            <helyszin>
                <es_orszag>Franciaország</es_orszag>
                <varos>Montpellier</varos>
                <hely>Sud de France Arena</hely>
            </helyszin>
        </esemeny>
        <esemeny es_azonosito = "2" csapat_nev = "JD Gaming">
            <es_nev>MSI 2023</es_nev>
            <ev>2023</ev>
            <nyeremeny>50000</nyeremeny>
            <helyszin>
                <es_orszag>Anglia</es_orszag>
                <varos>London</varos>
                <hely>Queen Elizabeth Olympic Park</hely>
            </helyszin>
        </esemeny>
        <esemeny es_azonosito = "3" csapat_nev = "T1">
            <es_nev>Worlds 2023</es_nev>
            <ev>2023</ev>
            <nyeremeny>445000</nyeremeny>
            <helyszin>
                <es_orszag>Dél-Korea</es_orszag>
                <varos>Seul</varos>
                <hely>Gocheok Sky Dome</hely>
            </helyszin>
        </esemeny>
    </esemenyek>

</LoL_WIQPM2>
